baseURL = "https://demaindargile.com/"
sectionPagesMenu = "main"
DefaultContentLanguage = "fr"

[languages]
  [languages.fr]
    title = "Demain d'Argile"
    weight = 1
    languageName = "FR"

      [[languages.fr.menu.main]]
        name = "Accueil"
        url = "/"
        weight = 1
      [[languages.fr.menu.main]]
        name = "Images"
        url = "/images/"
        identifier = "images"
        weight = 2
      [[languages.fr.menu.main]]
        name = "Ressources"
        url = "/ressources/"
        identifier = "ressources"
        weight = 3
      [[languages.fr.menu.main]]
        name = "Blog"
        url = "/blog/"
        identifier = "blog"
        weight = 4
      [[languages.fr.menu.main]]
        name = "À propos"
        url = "/a-propos/"
        identifier = "a-propos"
        weight = 5

  [languages.en]
    title = "Words of Clay"
    weight = 2
    languageName = "EN"

      [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        name = "Images"
        url = "/en/images/"
        identifier = "images"
        weight = 2
      [[languages.en.menu.main]]
        name = "Ressources"
        url = "/en/ressources/"
        identifier = "ressources"
        weight = 3
      [[languages.en.menu.main]]
        name = "Blog"
        url = "/en/blog/"
        identifier = "blog"
        weight = 4
      [[languages.en.menu.main]]
        name = "About"
        url = "/en/a-propos/"
        identifier = "a-propos"
        weight = 5

[params]
  dateFormat = "Jan 2, 2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

[taxonomies]
  tag = "tags"
